Fix Nucleus unstable connection by adding `hostAliases`
The `omnicli` command works well on all host machines (i.e., localhost,
K8s head node, OVX node), but randomly fails in all K8s pods.

It can be reproduced by submitting a `sleep infinity` task and exec
into that K8s pod (See `README.md` for detailed instructions), and then
run the following:

```
root@<POD_ID>:/omnicli# ./omnicli ls omniverse://<NUCLEUS_HOSTNAME>
2025-01-01 00:00:00  empty-folder  omniverse Library
2025-01-01 00:00:00   mount-point  omniverse NVIDIA
2025-01-01 00:00:00        folder  omniverse Projects
2025-01-01 00:00:00        folder  omniverse Users

root@<POD_ID>:/omnicli# ./omnicli ls omniverse://<NUCLEUS_HOSTNAME>
Error: Connection
```

The chance of failure may be high enough to make Nucleus entirely
unusable. This issue persists when substituting `<NUCLEUS_HOSTNAME>`
with `<NUCLEUS_IP>`.

@timost1234 has observed that manually adding the Nucleus hostname
entry to `/etc/hosts` reliably solves the issue, potentially due to the
need of (reverse) DNS lookups.

However, I'm not entirely sure why `omnicli` randomly fails/succeeds if
the hostAlias is not set. In addition, I didn't set `hostAlias` for
quite some time and are sure that a previous set up had worked
perfectly fine for weeks or even months.

I hypothesize that this may be due to the DNS settings of our VPN node,
which isn't controlled by me. In addition, the random results may be
due to manually setting `capacity_requirements.dnsConfig.nameservers`
as a hack to resolve a previous internet connection issue.

In conclusion, `hostAlias` is required, even though the system might
sometimes function correctly without it.

Co-authored-by: timost1234 <timost1234@gmail.com>